#ifndef DEFINE_HPP
#define DEFINE_HPP

enum eType {
	SERVER = 0,
	CLIENT
};

enum eState {
	READ_REQUEST = 0,
	DONE_REQUEST,
	READ_FILE_RESPONSE,
	READ_CGI_RESPONSE,
	WRITE_FILE_RESPONSE,
	WRITE_CGI_RESPONSE,
	SEND_HEADER_RESPONSE,
	SEND_BODY_RESPONSE,
	DONE_RESPONSE,
	CLOSE_CONNECTION
};

static const long		TIMEOUT = 30;
static const int		MAX_EVENT = 1024; // TODO: I don't know optimal MAX_EVENT yet.
const int				BUFFER_SIZE = 1024;

#endif	//	DEFINE_HPP